### ISSUE TITLE
Forbid recreation of existing data models

### ISSUE THREAD

**Issue by DominicBoettger** [molecuel/elements#1]
Error when reconnecting the system.

/var/node/node_modules/mlcl_database/node_modules/mongoose/lib/index.js:341
      throw new mongoose.Error.OverwriteModelError(name);
            ^
OverwriteModelError: Cannot overwrite `user` model once compiled.
    at Mongoose.model (/var/node/node_modules/mlcl_database/node_modules/mongoose/lib/index.js:341:13)
    at mlcl_database.registerModel (/var/node/node_modules/mlcl_database/index.js:101:29)
    at setElementType (/var/node/node_modules/mlcl_elements/index.js:300:31)
    at setElementTypes (/var/node/node_modules/mlcl_elements/index.js:292:18)
    at checkInit (/var/node/node_modules/mlcl_elements/index.js:36:18)
    at null.<anonymous> (/var/node/node_modules/mlcl_elements/index.js:54:9)
    at emit (events.js:95:17)
    at NativeConnection.<anonymous> (/var/node/node_modules/mlcl_database/index.js:13:14)
    at NativeConnection.emit (events.js:92:17)

**Comment by DominicBoettger** [comment]
This is outdated caused by the rework of the whole elements module
